name: "SF Delete Obsolete Flows"
description: "Delete obsolete flows from Salesforce org to clean up unused flow versions"

inputs:
  target-env:
    description: "Salesforce Target Environment Alias"
    required: true

runs:
  using: "composite"
  steps:
    - name: ðŸ—‘ï¸ Delete Obsolete Flows
      shell: bash
      run: |
        TARGET_ENV="${{ inputs.target-env }}"
        
        echo "--- Starting Obsolete Flow Cleanup ---"
        echo "Target Environment: $TARGET_ENV"
        
        # Query for obsolete flows using Tooling API with JSON output
        echo "Querying for obsolete flows..."
        QUERY_RESULT=$(sf data query \
          --query "SELECT Id, Definition.DeveloperName, VersionNumber FROM Flow WHERE Status = 'Obsolete'" \
          --target-org "$TARGET_ENV" \
          --use-tooling-api \
          --json 2>/dev/null || echo '{"result":{"records":[]}}')
        
        # Extract records using jq
        FLOW_COUNT=$(echo "$QUERY_RESULT" | jq -r '.result.records | length')
        
        if [ "$FLOW_COUNT" -eq 0 ] || [ "$FLOW_COUNT" == "null" ]; then
          echo "âœ… No obsolete flows found. Nothing to delete."
          
          # Add to GitHub Step Summary
          echo "## ðŸ—‘ï¸ Obsolete Flow Cleanup" >> $GITHUB_STEP_SUMMARY
          echo "No obsolete flows found. Nothing to delete." >> $GITHUB_STEP_SUMMARY
          exit 0
        fi
        
        echo "Found $FLOW_COUNT obsolete flow version(s) to delete."
        echo ""
        
        # Process each flow
        DELETED_COUNT=0
        FAILED_COUNT=0
        
        for i in $(seq 0 $((FLOW_COUNT - 1))); do
          FLOW_ID=$(echo "$QUERY_RESULT" | jq -r ".result.records[$i].Id")
          FLOW_NAME=$(echo "$QUERY_RESULT" | jq -r ".result.records[$i].Definition.DeveloperName // \"Unknown\"")
          VERSION_NUMBER=$(echo "$QUERY_RESULT" | jq -r ".result.records[$i].VersionNumber // \"?\"")
          
          # Skip if ID is invalid
          if [ -z "$FLOW_ID" ] || [ "$FLOW_ID" == "null" ]; then
            echo "âš ï¸ Skipping record with invalid ID"
            continue
          fi
          
          echo "Deleting: $FLOW_NAME (Version: $VERSION_NUMBER, Id: $FLOW_ID)"
          
          if sf data delete record \
            --sobject Flow \
            --record-id "$FLOW_ID" \
            --target-org "$TARGET_ENV" \
            --use-tooling-api 2>&1; then
            DELETED_COUNT=$((DELETED_COUNT + 1))
            echo "  âœ“ Deleted successfully"
          else
            FAILED_COUNT=$((FAILED_COUNT + 1))
            echo "  âœ— Failed to delete (may be referenced or protected)"
          fi
        done
        
        echo ""
        echo "--- Obsolete Flow Cleanup Summary ---"
        echo "Total processed: $FLOW_COUNT"
        echo "Successfully deleted: $DELETED_COUNT"
        echo "Failed to delete: $FAILED_COUNT"
        
        if [ "$DELETED_COUNT" -gt 0 ]; then
          echo "âœ… Obsolete flow cleanup completed successfully"
        else
          echo "â„¹ï¸ No flows were deleted"
        fi
        
        # Add to GitHub Step Summary
        echo "## ðŸ—‘ï¸ Obsolete Flow Cleanup" >> $GITHUB_STEP_SUMMARY
        echo "| Metric | Count |" >> $GITHUB_STEP_SUMMARY
        echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY
        echo "| Obsolete flows found | $FLOW_COUNT |" >> $GITHUB_STEP_SUMMARY
        echo "| Successfully deleted | $DELETED_COUNT |" >> $GITHUB_STEP_SUMMARY
        echo "| Failed to delete | $FAILED_COUNT |" >> $GITHUB_STEP_SUMMARY
