
name: 'SF Code Scanner'
description: 'Run Salesforce Code Analyzer on Apex classes'

inputs:
  apex-classes:
    description: 'Comma-separated list of Apex class paths to scan'
    required: true
  output-dir:
    description: 'Output directory for scanner results'
    required: false
    default: 'codeanalyzeroutput'
  severity:
    description: 'Severity level of a found violation that must be met or exceeded to cause this command to fail with a non-zero exit code.'
    required: false
    default: '2'

outputs:
  report-exists:
    description: 'Whether a code scanner report was generated'
    value: ${{ steps.code_analyzer.outputs.codeScannerReportExists }}

runs:
  using: 'composite'
  steps:
    - name: 🛡️ Run Code Analyzer
      id: code_analyzer
      shell: bash
      continue-on-error: true
      run: |
        APEX_CLASSES="${{ inputs.apex-classes }}"
        OUTPUT_DIR="${{ inputs.output-dir }}"
        SEVERITY="${{ inputs.severity }}"
        
        # Check if apex classes are provided
        if [ -z "$APEX_CLASSES" ] || [ "$APEX_CLASSES" = "./**/*.cls" ]; then
          echo "No specific Apex classes to scan or scanning all classes."
          
          # For full deployment, check if there are any cls files
          if [ "$APEX_CLASSES" = "./**/*.cls" ]; then
            APEX_CLASSES=$(find . -name "*.cls" -type f | head -100 | tr '\n' ',' | sed 's/,$//')
          fi
        fi
        
        if [ -z "$APEX_CLASSES" ]; then
          echo "Nothing to scan (no Apex classes found)."
          echo "codeScannerReportExists=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "--- Starting Code Scan ---"
        echo "Scanning: $APEX_CLASSES"
        
        # Create output directory
        mkdir -p "$OUTPUT_DIR"
        
        # Run the scan
        sf code-analyzer run \
          -s "$SEVERITY" \
          -t "$APEX_CLASSES" \
          -f "$OUTPUT_DIR/code-scanner-results.csv"
        
        # Set output variable to track if a report was generated
        if [ -f "$OUTPUT_DIR/code-scanner-results.csv" ]; then
          echo "codeScannerReportExists=true" >> $GITHUB_OUTPUT
          echo "✅ Code scan completed. Report generated."
        else
          echo "codeScannerReportExists=false" >> $GITHUB_OUTPUT
          echo "⚠️ Code scan completed but no report generated."
        fi


